from django.urls import path
from . import views

urlpatterns = [
    path('', views.BookList.as_view(), name='book_list'),
    path('view/<str:pk>', views.BookDetail.as_view(), name='book_view'),
    path('new', views.BookCreate.as_view(), name='book_new'),
    path('edit/<str:pk>', views.BookUpdate.as_view(), name='book_edit'),
    path('delete/<str:pk>', views.BookDelete.as_view(), name='book_delete'),
    path('author', views.AuthorList.as_view(), name='author_list'),
    path('author/view/<str:pk>', views.AuthorDetail.as_view(), name='author_view'),
    path('author/new', views.AuthorCreate.as_view(), name='author_new'),
    path('author/edit/<str:pk>', views.AuthorUpdate.as_view(), name='author_edit'),
    path('author/delete/<str:pk>', views.AuthorDelete.as_view(), name='author_delete'),
    path('customer', views.CustomerList.as_view(), name='customer_list'),
    path('customer/view/<str:pk>', views.CustomerDetail.as_view(), name='customer_view'),
    path('customer/new', views.CustomerCreate.as_view(), name='customer_new'),
    path('customer/edit/<str:pk>', views.CustomerUpdate.as_view(), name='customer_edit'),
    path('customer/delete/<str:pk>', views.CustomerDelete.as_view(), name='customer_delete'),
    path('sale', views.SaleList.as_view(), name='sale_list'),
    path('sale/view/<int:pk>', views.SaleDetail.as_view(), name='sale_view'),
    path('sale/new', views.SaleCreate.as_view(), name='sale_new'),
    path('sale/edit/<int:pk>', views.SaleUpdate.as_view(), name='sale_edit'),
    path('sale/delete/<int:pk>', views.SaleDelete.as_view(), name='sale_delete'),
    path('publisher', views.PublisherList.as_view(), name='publisher_list'),
    path('publisher/view/<str:pk>', views.PublisherDetail.as_view(), name='publisher_view'),
    path('publisher/new', views.PublisherCreate.as_view(), name='publisher_new'),
    path('publisher/edit/<str:pk>', views.PublisherUpdate.as_view(), name='publisher_edit'),
    path('publisher/delete/<str:pk>', views.PublisherDelete.as_view(), name='publisher_delete'),
]