# Generated by Django 3.1.7 on 2021-03-30 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('bornIn', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1200), django.core.validators.MaxValueValidator(2021)], verbose_name='Born In')),
                ('diedIn', models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1200), django.core.validators.MaxValueValidator(2021)], verbose_name='Died In')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('foundedIn', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1200), django.core.validators.MaxValueValidator(2021)], verbose_name='Founded In')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('president', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('publishedIn', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1200), django.core.validators.MaxValueValidator(2021)], verbose_name='Published In')),
                ('pages', models.PositiveIntegerField()),
                ('author', models.ManyToManyField(to='bookapp.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.publication')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.customer')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('customer', 'book')},
            },
        ),
    ]
